/**
 * core/reporters/suiteReporter.js
 *
 * Custom Playwright reporter that generates a single aggregated suite-report.html
 * at the top of the suite time folder, summarising all scripts in the run.
 *
 * Folder output:
 *   playwright-report/
 *   └── [date]/
 *       └── [suite-name]/
 *           └── [HH-MM-SS]/
 *               ├── suite-report.html      ← generated by this reporter
 *               ├── register_by_email-bdd/
 *               │   └── index.html
 *               └── register_by_phone-bdd/
 *                   └── index.html
 */
'use strict';

const fs = require('fs');
const path = require('path');

class SuiteReporter {
  constructor(options = {}) {
    this.outputDir = options.outputFolder
      ? path.resolve(options.outputFolder)
      : null;
    this.suiteName = options.suiteName || process.env.QA_SUITE_NAME || '';
    this.suiteLabel = options.suiteLabel || '';
    this.startTime = new Date();
    this._specMap = new Map();
    this._totals = { passed: 0, failed: 0, skipped: 0, total: 0, durationMs: 0 };
  }

  onBegin() {
    this._specMap.clear();
    this._totals = { passed: 0, failed: 0, skipped: 0, total: 0, durationMs: 0 };
    this.startTime = new Date();
  }

  onTestEnd(test, result) {
    const specTitle = this._rootSpecTitle(test);
    if (!this._specMap.has(specTitle)) {
      this._specMap.set(specTitle, { passed: 0, failed: 0, skipped: 0, total: 0, durationMs: 0 });
    }
    const spec = this._specMap.get(specTitle);
    const status = result.status || 'failed';
    spec.total++;
    spec.durationMs += result.duration || 0;
    if (status === 'passed') spec.passed++;
    else if (status === 'skipped') spec.skipped++;
    else spec.failed++;

    this._totals.total++;
    this._totals.durationMs += result.duration || 0;
    if (status === 'passed') this._totals.passed++;
    else if (status === 'skipped') this._totals.skipped++;
    else this._totals.failed++;
  }

  async onEnd(result) {
    if (!this.outputDir) return;
    fs.mkdirSync(this.outputDir, { recursive: true });

    const endTime = new Date();
    const durationSec = ((endTime - this.startTime) / 1000).toFixed(1);
    const passRate = this._totals.total
      ? Math.round((this._totals.passed / this._totals.total) * 100)
      : 0;

    const html = this._render({
      suiteName: this.suiteName,
      suiteLabel: this.suiteLabel,
      startTime: this.startTime,
      endTime,
      durationSec,
      passRate,
      totals: this._totals,
      specs: [...this._specMap.entries()].map(([title, stat]) => ({ title, ...stat })),
      exitStatus: result ? result.status : 'unknown',
    });

    fs.writeFileSync(path.join(this.outputDir, 'suite-report.html'), html, 'utf8');
  }

  _rootSpecTitle(test) {
    const tp = typeof test.titlePath === 'function' ? test.titlePath() : [];
    return tp[0] || test.title || 'Unknown Spec';
  }

  _esc(str) {
    return String(str != null ? str : '')
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  _fmtDuration(ms) {
    const s = Math.round(ms / 1000);
    return s < 60 ? s + 's' : Math.floor(s / 60) + 'm ' + (s % 60) + 's';
  }

  _fmtTime(d) {
    return d.toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit', second: '2-digit' });
  }

  _fmtDate(d) {
    return d.toLocaleDateString('vi-VN', { day: '2-digit', month: '2-digit', year: 'numeric' });
  }

  _statusColor(t) {
    if (t.failed > 0) return '#cf222e';
    if (t.total > 0 && t.skipped === t.total) return '#9a6700';
    return '#1a7f37';
  }

  _statusLabel(t) {
    if (t.failed > 0) return 'FAILED';
    if (t.total > 0 && t.skipped === t.total) return 'SKIPPED';
    return 'PASSED';
  }

  _specRows(specs) {
    if (specs.length === 0) {
      return '<tr><td colspan="9" style="text-align:center;color:#656d76;padding:20px">Không có dữ liệu</td></tr>';
    }
    return specs.map((s, idx) => {
      const rate = s.total ? Math.round((s.passed / s.total) * 100) : 0;
      const color = this._statusColor(s);
      const label = this._statusLabel(s);
      const barColor = s.failed > 0 ? '#cf222e' : '#1a7f37';
      return [
        '<tr>',
        '<td class="spec-num">' + (idx + 1) + '</td>',
        '<td class="spec-title">' + this._esc(s.title) + '</td>',
        '<td><span class="badge" style="background:' + color + '">' + label + '</span></td>',
        '<td class="num">' + s.passed + '</td>',
        '<td class="num fail">' + s.failed + '</td>',
        '<td class="num skip">' + s.skipped + '</td>',
        '<td class="num">' + s.total + '</td>',
        '<td><div class="bar-wrap"><div class="bar-fill" style="width:' + rate + '%;background:' + barColor + '"></div></div><span class="bar-pct">' + rate + '%</span></td>',
        '<td class="num dur">' + this._fmtDuration(s.durationMs) + '</td>',
        '</tr>',
      ].join('');
    }).join('\n');
  }

  _render({ suiteName, suiteLabel, startTime, endTime, durationSec, passRate, totals, specs }) {
    const overallColor = totals.failed > 0 ? '#cf222e' : '#1a7f37';
    const overallLabel = totals.failed > 0 ? 'FAILED' : 'PASSED';
    const overallBg = totals.failed > 0
      ? 'linear-gradient(135deg,#fff1f0 0%,#fff 100%)'
      : 'linear-gradient(135deg,#f0fff4 0%,#fff 100%)';
    const donut = 'conic-gradient(' + overallColor + ' 0 ' + passRate + '%, #e6edf3 ' + passRate + '% 100%)';

    return '<!DOCTYPE html>\n<html lang="vi">\n<head>\n<meta charset="UTF-8"/>\n<meta name="viewport" content="width=device-width,initial-scale=1"/>\n<title>Suite Report \u2014 ' + this._esc(suiteName) + '</title>\n<style>\n*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\nbody{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#f6f8fa;color:#1f2328;min-height:100vh}\n.suite-header{background:' + overallBg + ';border-bottom:1px solid #d0d7de;padding:28px 36px;display:flex;align-items:center;gap:28px}\n.suite-donut{flex:0 0 auto;width:100px;height:100px;border-radius:50%;background:' + donut + ';display:grid;place-items:center;box-shadow:inset 0 0 0 14px #fff;font-size:22px;font-weight:700;color:' + overallColor + '}\n.suite-meta{flex:1}\n.suite-meta h1{font-size:22px;font-weight:700;margin-bottom:4px}\n.suite-meta .sub{color:#656d76;font-size:13px;line-height:1.8}\n.badge-overall{display:inline-block;padding:4px 14px;border-radius:20px;font-size:13px;font-weight:700;color:#fff;background:' + overallColor + ';margin-bottom:8px}\n.stats-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;padding:20px 36px;max-width:1280px;margin:0 auto}\n.stat-card{background:#fff;border:1px solid #d0d7de;border-radius:8px;padding:16px 20px}\n.stat-label{font-size:12px;color:#656d76;margin-bottom:6px}\n.stat-value{font-size:32px;font-weight:700}\n.stat-value.pass{color:#1a7f37}.stat-value.fail{color:#cf222e}.stat-value.skip{color:#9a6700}.stat-value.total{color:#0969da}\n.table-wrap{max-width:1280px;margin:0 auto 32px;padding:0 36px}\n.section-title{font-size:16px;font-weight:700;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid #d0d7de;display:flex;align-items:center;gap:8px}\ntable{width:100%;border-collapse:collapse;background:#fff;border:1px solid #d0d7de;border-radius:8px;overflow:hidden;font-size:13px}\nthead tr{background:#f6f8fa}\nth{padding:10px 14px;text-align:left;font-size:12px;font-weight:600;color:#656d76;text-transform:uppercase;letter-spacing:.04em;border-bottom:1px solid #d0d7de;white-space:nowrap}\ntd{padding:10px 14px;border-bottom:1px solid #eaeef2;vertical-align:middle}\ntr:last-child td{border-bottom:none}\ntr:hover td{background:#f6f8fa}\n.spec-num{color:#656d76;width:36px;text-align:center}.spec-title{font-weight:500}\n.num{text-align:right;font-variant-numeric:tabular-nums}.num.fail{color:#cf222e;font-weight:600}.num.skip{color:#9a6700}.num.dur{color:#656d76}\n.badge{display:inline-block;padding:2px 10px;border-radius:20px;font-size:11px;font-weight:700;color:#fff;white-space:nowrap}\n.bar-wrap{display:inline-block;width:80px;height:6px;background:#e6edf3;border-radius:3px;overflow:hidden;vertical-align:middle;margin-right:6px}\n.bar-fill{height:100%;border-radius:3px}\n.bar-pct{font-size:12px;color:#656d76;vertical-align:middle}\n.footer{text-align:center;color:#656d76;font-size:12px;padding:16px 36px 28px}\n@media(max-width:720px){.suite-header{flex-direction:column;padding:20px 16px}.stats-grid{grid-template-columns:repeat(2,1fr);padding:16px}.table-wrap{padding:0 16px}}\n</style>\n</head>\n<body>\n<header class="suite-header">\n  <div class="suite-donut">' + passRate + '%</div>\n  <div class="suite-meta">\n    <span class="badge-overall">' + this._esc(overallLabel) + '</span>\n    <h1>\u{1F4CB} ' + this._esc(suiteLabel || suiteName || 'Test Suite Report') + '</h1>\n    <div class="sub">\n      Suite: <strong>' + this._esc(suiteName) + '</strong> &nbsp;&middot;&nbsp;\n      Ng\u00e0y: <strong>' + this._esc(this._fmtDate(startTime)) + '</strong> &nbsp;&middot;&nbsp;\n      B\u1eaft \u0111\u1ea7u: <strong>' + this._esc(this._fmtTime(startTime)) + '</strong> &nbsp;&middot;&nbsp;\n      K\u1ebft th\u00fac: <strong>' + this._esc(this._fmtTime(endTime)) + '</strong> &nbsp;&middot;&nbsp;\n      T\u1ed5ng th\u1eddi gian: <strong>' + this._esc(durationSec) + 's</strong>\n    </div>\n  </div>\n</header>\n<div class="stats-grid">\n  <div class="stat-card"><div class="stat-label">T\u1ed5ng s\u1ed1 test</div><div class="stat-value total">' + totals.total + '</div></div>\n  <div class="stat-card"><div class="stat-label">\u2705 Passed</div><div class="stat-value pass">' + totals.passed + '</div></div>\n  <div class="stat-card"><div class="stat-label">\u274c Failed</div><div class="stat-value fail">' + totals.failed + '</div></div>\n  <div class="stat-card"><div class="stat-label">\u23ed\ufe0f Skipped</div><div class="stat-value skip">' + totals.skipped + '</div></div>\n</div>\n<div class="table-wrap">\n  <div class="section-title">\n    \ud83d\uddc2\ufe0f Chi ti\u1ebft theo Script\n    <span style="font-size:13px;font-weight:400;color:#656d76">(' + specs.length + ' script)</span>\n  </div>\n  <table>\n    <thead><tr><th>#</th><th>Script</th><th>Status</th><th style="text-align:right">Pass</th><th style="text-align:right">Fail</th><th style="text-align:right">Skip</th><th style="text-align:right">Total</th><th>Pass rate</th><th style="text-align:right">Th\u1eddi gian</th></tr></thead>\n    <tbody>\n      ' + this._specRows(specs) + '\n    </tbody>\n  </table>\n</div>\n<div class="footer">Generated by ScriptFlow QA Framework &nbsp;&middot;&nbsp; Suite: ' + this._esc(suiteName) + ' &nbsp;&middot;&nbsp; ' + this._esc(this._fmtDate(endTime)) + ' ' + this._esc(this._fmtTime(endTime)) + '</div>\n</body>\n</html>';
  }
}

module.exports = SuiteReporter;
